spring:
  application:
    name: eureka-server
  main:
    banner-mode: off
server:
  port: 9092
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0