spring:
  application:
    name: auth-service
  liquibase:
    change-log: classpath:db.changelog/db-changelog-master.xml
  datasource:
    url: jdbc:h2:file:./data/auth-service;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
  h2:
    console:
      enabled: false
      path: /h2-console
  config:
    import: optional:classpath:application-secrets.yml
logging:
  pattern:
    correlation: "[%X{traceId:-},%X{spanId:-}]"
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9092/eureka/
jwt:
  expiration: 3600000  # 1 hour in milliseconds